# Generated by Django 4.0.2 on 2022-03-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_painting_like_count_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='painting',
            field=models.ImageField(default='null', upload_to='paintings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.FileField(upload_to='upload_images'),
        ),
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
        migrations.AlterModelTable(
            name='painting',
            table='painting',
        ),
    ]
