# Generated by Django 4.0.2 on 2022-03-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0003_painting_painting_alter_painting_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='image',
            new_name='uploads_image',
        ),
    ]
