# Generated by Django 4.0.2 on 2022-03-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_rename_image_painting_uploads_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='uploads_image',
            new_name='upload_image',
        ),
    ]
