# Generated by Django 4.0.3 on 2022-03-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0005_rename_uploads_image_painting_upload_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painting',
            old_name='painting',
            new_name='image',
        ),
    ]
