# Generated by Django 4.0.3 on 2022-03-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_rename_painting_painting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='upload_image',
            field=models.FileField(blank=True, upload_to='upload_images'),
        ),
    ]
