# Generated by Django 4.0.3 on 2022-03-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0007_alter_painting_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(blank=True, upload_to='paintings'),
        ),
    ]
